---
- name: set up
  hosts: localhost
  connection: local
  gather_facts: no

  roles:
    - geerlingguy.dotfiles
    - homebrew
    - homebrew_cask
    - mac_app_store
    - macos

  vars:
    dotfiles_repo: "git@github.com:m-shimao/dotfiles.git"
    dotfiles_repo_version: main
    dotfiles_repo_local_destination: "~/dotfiles"
    dotfiles_files:
      - .gitconfig
      - .zshrc
      - .config/nvim/init.vim
