---
- block:

  - name: DNS setting
    shell: networksetup -setdnsservers Wi-Fi 8.8.8.8 8.8.4.4
    tags:
      - dns

  - block:
    # check defaults
    # $ defaults read
    - name: set osx defaults
      osx_defaults:
        domain: "{{ item.domain }}"
        key: "{{ item.key }}"
        type: "{{ item.type }}"
        value: "{{ item.value }}"
      with_items: "{{ settings }}"
    tags:
      - osx_defaults

  - block:
    # neovim setting
    - name: create a directory autoload
      file:
        path: ~/.local/share/nvim/site/autoload
        state: directory
        mode: 0710
        owner: shimao
        group: staff
    - name: create a directory ~/.cache/tmp
      file:
        path: ~/.cache/tmp
        state: directory
        mode: 0751
        owner: shimao
        group: staff
    - name: download vim-plug
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: ~/.local/share/nvim/site/autoload
        mode: 0644
        owner: shimao
        group: staff
    - name: PlugInstall
      shell: nvim -c PlugInstall -c q -c q
    tags:
      - vim

  tags:
    - macos
