---
- block:

  - name: DNS setting
    shell: networksetup -setdnsservers Wi-Fi 8.8.8.8 8.8.4.4
    tags:
      - dns

  - block:
    # check defaults
    # $ defaults read
    - name: set osx defaults
      osx_defaults:
        domain: "{{ item.domain }}"
        key: "{{ item.key }}"
        type: "{{ item.type }}"
        value: "{{ item.value }}"
      with_items: "{{ settings }}"
    tags:
      - osx_defaults

  - block:
    # bash setting
    - name: copy ~/.bash_profile template
      template:
        src: .bash_profile.j2
        dest: ~/.bash_profile
        owner: m-shimao
        group: staff
        mode: 0600

    - name: copy ~/.bashrc template
      template:
        src: .bashrc.j2
        dest: ~/.bashrc
        owner: m-shimao
        group: staff
        mode: 0600
    tags:
      - bash

  - block:
    # git setting
    - name: copy ~/.gitconfig template
      copy:
        src: gitconfig
        dest: ~/.gitconfig
        owner: m-shimao
        group: staff
        mode: 0644

    - name: copy ~/.commit_template template
      copy:
        src: commit_template
        dest: ~/.commit_template
        owner: m-shimao
        group: staff
        mode: 0644
    tags:
      - git

  - block:
    # vim setting
    - name: pip install for linter & fixer
      pip:
        name:
          - flake8
          - mypy
          - autopep8
          - isort
        executable: pip3
    - name: create a directory ~/.vim/autoload
      file:
        path: ~/.vim/autoload
        state: directory
        mode: 0710
        owner: m-shimao
        group: staff
    - name: create a directory ~/.cache/tmp
      file:
        path: ~/.cache/tmp
        state: directory
        mode: 0751
        owner: m-shimao
        group: staff
    - name: download vim-plug
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: ~/.vim/autoload
        mode: 0644
        owner: m-shimao
        group: staff
    - name: copy vimrc
      copy:
        src: vimrc
        dest: ~/.vimrc
        owner: m-shimao
        group: staff
        mode: 0751
    - name: PlugInstall
      shell: vim -c PlugInstall -c q -c q
    tags:
      - vim

  tags:
    - macos
