---
packages:
  - { id: 302584613, name: Kindle }
  - { id: 409201541, name: Pages }
  - { id: 409203825, name: Numbers }
  - { id: 409183694, name: Keynote }
  - { id: 497799835, name: Xcode }
  - { id: 539883307, name: Line }
