---
- block:

  - name: homebrew update
    homebrew:
      update_homebrew: true

  - name: upgrade homebrew
    homebrew:
      upgrade_all: true

  - name: homebrew packages install
    homebrew:
      name: "{{ item.name }}"
      state: "{{ item.state | default('present') }}"
    with_items: "{{ packages }}"

  - name: install docker-tags homebrew package
    homebrew:
      name:
        - koki-develop/tap/docker-tags

  tags:
    - homebrew
