---
- block:

  - name: homebrew update
    homebrew:
      update_homebrew: true

  - name: homebrew tap
    homebrew_tap:
      name: "{{ item }}"
      state: present
    with_items: "{{ taps }}"

  - name: homebrew packages install
    homebrew:
      name: "{{ item.name }}"
      state: "{{ item.state | default('present') }}"
    with_items: "{{ packages }}"

  - block:
    # node.js
    - name: create a directory ~/.nodebrew/src
      file:
        path: ~/.nodebrew/src
        state: directory
        mode: 0710
        owner: m-shimao
        group: staff
    - name: install node.js
      shell: nodebrew install-binary latest
      ignore_errors: True
    - name: use latest version
      shell: nodebrew use $(nodebrew list | head -n1)
    tags:
      - node

  tags:
    - homebrew
