---
- block:

  - name: upgrade all casks
    homebrew_cask:
      upgrade_all: true

  - name: homebrew cask packages install 'item.name'
    environment:
      HOMEBREW_CASK_OPTS: --appdir=/Applications
    homebrew_cask:
      name: "{{ item.name }}"
      state: "{{ item.state | default('present') }}"
    with_items: "{{ packages }}"

  tags:
    - homebrew
    - homebrew_cask
